name: Build VPK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Use official prebuilt VitaSDK Docker container
    container:
      image: vitasdk/vitasdk:latest

    steps:
      # Step 1: Checkout the repo
      - uses: actions/checkout@v3

      # Step 2: Build the app
      - name: Build PsvitaSpot
        run: |
          mkdir build
          cd build
          cmake ..
          make

      # Step 3: Upload the VPK artifact
      - name: Upload VPK
        uses: actions/upload-artifact@v4
        with:
          name: PsvitaSpot
          path: build/*.vpk
